name: ${name}
main: ${main}
version: ${version}
author: ${author}
description: ${description}
api-version: ${apiversion}
website: ${website}
depend:
  - kLanguage
  - kLoader
commands:
  morning:
    description: Set the time to morning
    usage: /morning [<world>]
    aliases: [ morgen ]
  day:
    description: Set the time to day
    usage: /day [<world>]
    aliases: [ tag ]
  midday:
    description: Set the time to midday
    usage: /midday [<world>]
    aliases: [ mittag ]
  evening:
    description: Set the time to evening
    usage: /evening [<world>]
    aliases: [ abend ]
  night:
    description: Set the time to night
    usage: /night [<world>]
    aliases: [ nacht ]
  tpa:
    description: Request a teleport to another player
    usage: /tpa <player>
    aliases: [ tpanfrage ]
  tpaccept:
    description: Accept a teleport request
    usage: /tpaccept <player>
    aliases: [ tpakzeptieren ]
  tpdeny:
    description: Deny a teleport request
    usage: /tpdeny <player>
    aliases: [ tpablehnen ]
  tplist:
    description: List all teleport request
    usage: /tplist
    aliases: [ tpanfragen ]
  gamemode:
    description: Change the gamemode of a player
    usage: /gamemode <gamemode> [<player>]
    aliases: [ gm ]
  suicide:
    description: Kills the executor
    usage: /suicide
    aliases: [ suizid, selbstmord ]
  f3d:
    description: Clears your chat
    usage: /f3d
    aliases: [ clearmychat, meinenchatleeren ]
  fly:
    description: Toggles flight
    usage: /fly [<player>]
    aliases: [ flight, flug, flugmodus, fliegen ]
  speed:
    description: Changes walking/flying speed
    usage: /speed <speed> [<player>]
    aliases: [ geschwindigkeit ]
  chatclear:
    description: Clears the chat for all players
    usage: /chatclear
    aliases: [ cc, chatleeren ]
  teleportplayer:
    description: Teleports players to each other
    usage: /teleportplayer <player> [<player>]
    aliases: [ tpp ]
  freeze:
    description: Freezes a player so that they cannot move
    usage: /freeze [<player>]
    aliases: [ einfrieren ]
  vanish:
    description: Makes a player invisible for all other players
    usage: /vanish [<player>]
    aliases: [ verschwinden, v ]
  heal:
    description: Heals a player
    usage: /heal [<player>]
    aliases: [ heilen ]
  feed:
    description: Feeds a player
    usage: /feed [<player>]
    aliases: [ essen ]
  repair:
    description: Repairs the item in your hand
    usage: /repair [<player>]
    aliases: [ reparieren ]
  inventorysee:
    description: Opens the inventory of a player
    usage: /inventorysee [<player>]
    aliases: [ invsee, inv, inventory, inventar ]
  armorsee:
    description: Opens the armor inventory of a player
    usage: /armorsee [<player>]
    aliases: [ armor, armsee, ruestung ]
  home:
    description: Teleports you to your home
    usage: /home [<home>]
    aliases: [ zuhause, homes ]
  sethome:
    description: Sets your home
    usage: /sethome [<home>]
    aliases: [ newhome, delhomes, newhomes, zuhausefestlegen ]
  deletehome:
    description: Deletes your home
    usage: /deletehome [<home>]
    aliases: [ delhome, removehome, removehomes, zuhauseloeschen ]
  warp:
    description: Teleports you to a warp
    usage: /warp <warp>
    aliases: [ warps ]
  setwarp:
    description: Sets a warp
    usage: /setwarp <warp>
    aliases: [ newwarp, addwarp ]
  deletewarp:
    description: Deletes a warp
    usage: /deletewarp <warp>
    aliases: [ delwarp, removewarp ]
  spawn:
    description: Teleports you to the spawn
    usage: /spawn
  kessentials:
    description: Main command for kEssentials
    usage: /kessentials
    aliases: [ essentials, kessential ]
  material:
    description: Get the name of the material in your hand
    usage: /material
    aliases: [ mat ]
  enchantingtable:
    description: Opens a enchanting table
    usage: /enchantingtable <level> <level> <level> [<player>]
    aliases: [ verzauberungstisch, enchantmenttable ]
  workbench:
    description: Opens a workbench
    usage: /workbench [<player>]
    aliases: [ werkbank, craftingtable, craft, crafting ]
  anvil:
    description: Opens a anvil
    usage: /anvil [<player>]
    aliases: [ amboss ]
  enderchest:
    description: Opens a enderchest
    usage: /enderchest [<player>]
    aliases: [ ec, enderkiste ]
  team:
    description: Manage clans/teams
    usage: /team <create|join|leave> <name>
  link:
    description: Generates a Discord verification code
    usage: /link
  botreload:
    description: Reloads discord.conf
    usage: /botreload
  bot:
    description: Discord bot commands
    usage: /bot say <text>
